export const ACCIONES_MONGOOSE = {
    AGGREGATE: 'aggregate',
    COUNT: 'count',
    COUNT_DOCUMENTS: 'countDocuments',
    DELETE_ONE: 'deleteOne',
    DELETE_MANY: 'deleteMany',
    ESTIMATED_DOCUMENT_COUNT: 'estimatedDocumentCount',
    FIND: 'find',
    FIND_ONE: 'findOne',
    FIND_ONE_AND_DELETE: 'findOneAndDelete',
    FIND_ONE_AND_REMOVE: 'findOneAndRemove',
    FIND_ONE_AND_REPLACE: 'findOneAndReplace',
    FIND_ONE_AND_UPDATE: 'findOneAndUpdate',
    INIT: 'init',
    INSERT_MANY: 'insertMany',
    REMOVE: 'remove',
    REPLACE_ONE: 'replaceOne',
    SAVE: 'save',
    UPDATE: 'update',
    UPDATE_ONE: 'updateOne',
    UPDATE_MANY: 'updateMany',
    VALIDATE: 'validate',
}

export const TRADUCCIONES_ACCIONES_MONGOOSE = {
    aggregate: 'consultar de manera agrupada',
    count: 'contar',
    countDocuments: 'contar elementos',
    deleteOne: 'eliminar uno',
    deleteMany: 'eliminar varios',
    estimatedDocumentCount: 'contar de manera estimada elementos',
    find: 'encontrar',
    findOne: 'encontrar uno',
    findOneAndDelete: 'encontrar uno y eliminar',
    findOneAndRemove: 'encontar uno y remover',
    findOneAndReplace: 'encontrar uno y reemplazar',
    findOneAndUpdate: 'encontrar uno y actualizar',
    init: 'inicializar',
    insertMany: 'insertar varios',
    remove: 'remover',
    replaceOne: 'reemplazar uno',
    save: 'crear',
    update: 'actualizar',
    updateOne: 'actualizar uno',
    updateMany: 'actualizar varios',
    validate: 'validar',
}

export const NOMBRE_ROL_SUPER_ADMIN = 'SUPER ADMINISTRADOR'
export const NOMBRE_USUARIO_SUPER_ADMIN = 'Super Usuario'