services:
    app_perpetuus:
        image: kyostenas/perpetuus:latest
        restart: unless-stopped
        container_name: app_perpetuus
        stdin_open: true
        tty: true        
        volumes:
            - /volumenes-docker-peretuus/certificados:/etc/letsencrypt
            - /volumenes-docker-peretuus/datos-aplicacion:/datos-aplicacion
        ports:
            - 443:443
            - 80:80
        networks:
            - perpetuus_network
        environment:
            TZ: "America/Mexico_City"
networks:
    perpetuus_network:
        driver: bridge